### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by mwitz8** [youneuoy/M2TWEOP-luaPlugin#1]
Could you write a readme that describes the project structure and/or explains how to add functions? That way more people would find it easier to contribute and to actually write some LUA for their mods.

**Comment by yaneay** [comment]
> 
> 
> Could you write a readme that describes the project structure and/or explains how to add functions? That way more people would find it easier to contribute and to actually write some LUA for their mods.

It is possible. But I'm not sure if it will be interesting to anyone. If someone suddenly has a desire to take part, then I will gladly answer questions if they arise. Perhaps, in the course of such interactions, the readme will be created.
Now it seems to me that the structure of the project is quite clear and understandable, build occurs without additional actions, and so on. At least one person has already figured it out without my help and there have been no complaints from him.
Everything important for ordinary users is indicated in the readme of the main project and on the program website.

**Comment by mwitz8** [comment]
My bad -- I was trying to find the [main project](https://github.com/youneuoy/M2TWEOP-library). Google gave me this one and I assumed it was the main project. Sorry about that.
